apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: wordpress
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wordpress
  targetCPUUtilizationPercentage: 50
status:
  currentReplicas: 0
  desiredReplicas: 0
  
  
  
  
  And we can apply autoscaling useing this command
  
  kubectl autoscale deployment test --cpu-percent=50 --min=1 --max=10 --dry-run -o yaml
